name: 'merge-pdfs'
description: 'Combines PDFs'

inputs:
  files:
    description: 'The list of the .pdf files'
    required: true
    default: ''
  output:
    description: 'The name of the output file'
    required: true
    default: 'combined.pdf'
    
runs:
  using: "docker"
  image: "Dockerfile"
