name: 'combine-pdfs'
description: 'Combines PDFs'

inputs:
  INPUTFOLDER:  # id of input
    description: 'Who to greet'
    required: true
    default: 'resources'
    
runs:
  using: "docker"
  image: "Dockerfile"

# branding:
#   icon: "mic"
#   color: "purple"
