name: example
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: CombinePDFS
    runs-on: ubuntu-latest
    env:
      files: |
        resources/b.pdf
        resources/a.pdf
        resources/c (1).pdf
      output: example.pdf
    steps:
      - uses: actions/checkout@v4
      - uses: Oyami-Srk/MergePDFs-action@v1
        with:
          files: ${{env.files}}
          output: ${{env.output}}
      - name: Upload combined pdf
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.output}}
          path: ${{env.output}}
