on: [push]

jobs:
  build:
    name: CombinePDFS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          INPUTFOLDER: resources
      - name: Upload combined pdf
        uses: actions/upload-artifact@v2
        with:
          name: combined-pdf
          path: resources/combined.pdf
